### PR TITLE
WIP: Preliminary work on Readme

### PR DESCRIPTION
**Pull request by Gamerguy123lo**

### CODE REVIEW

**Comment by CSSolomon** [comment]
This Pull request is the other way around. You want to push Readme into main, not main into readme.

**Comment by CSSolomon** [comment]
The `README.md` file is incomplete. There's no need to say "welcome", instead talk about the program directly. Answer the following questions:

1. Why are you writing this code?
2. What language will you be using?
3. What technologies?
4. How can you describe each technology in a few words?
5. What are the sources you studied to write this `README.md`?

**Comment by CSSolomon** [comment]
Your commit messages **need** to be more than "Update README.md". Each commit should contain a single conceptual unit of work, i.e. don't change formatting and write a function in the same one and your commit message should give details on the commit work. E.g.

* What work did you do ("Write first version of add function")
* What the changes signify ("Create function with basic functionality. Add tests to verify normal use OK")
* Why you undertook this effort if relevant
* ...

Try searching "good commit messages" and reading articles about the topic. E.g. https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

**Comment by Gamerguy123lo** [comment]
@CSSolomon I opened up a new repository to change the branch merge. I updated the Readme, added more info features and the source of it. I also used more description on the commit messages.

**Pull request closed without merging**
